export class PersonalLoanRequest{
    quote_id:number;
    ApplicantDOB:string;
    ApplicantGender:string;
    ApplicantIncome:number;
    ApplicantNme:string;
    ApplicantObligations:number;
    ApplicantSource:number;
    BrokerId:number;
    LoanRequired:number;
    LoanTenure:number;
    api_source:string;
    empcode:string;
    FBA_id:number;
    loan_requestID:number;
    row_created_date:string;
    row_updated_date:string;
    quote_application_type:string;
    conversiondate:string;
    Type:string;
    TranType:number;
    isActive:number;
}