export class AuthenticationInputInfo {
    UserName:string;
    Password:string;
    OldPassword:string;
    FBAId:number;
    DeviceId:string;
    DeviceOS:string;
    DeviceName:string;
    IpAdd:string;
    LastLog:string;
    EmailId:string;
    TokenId:string;
    MobileNo:string;
    UserType:string;
    UserId:number;
    VersionNo:string;
    AppID:string;
    AppUSERID:string;
    AppPASSWORD:string;
}